-- Mo rong he thong quan tri, giu nguyen du lieu quiz hien co.

alter table public.profiles
  add column if not exists role text not null default 'user',
  add column if not exists is_banned boolean not null default false;

do $$ begin
  alter table public.profiles add constraint profiles_role_check check (role in ('admin', 'user'));
exception when duplicate_object then null;
end $$;

update public.profiles p
set role = case when u.raw_app_meta_data ->> 'role' = 'admin' then 'admin' else 'user' end
from auth.users u where u.id = p.id;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique check (length(trim(name)) > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.categories(name)
select distinct trim(category) from public.questions
where trim(category) <> ''
on conflict (name) do nothing;

alter table public.questions
  add column if not exists category_id bigint references public.categories(id) on delete restrict,
  add column if not exists difficulty text not null default 'medium',
  add column if not exists status text not null default 'published',
  add column if not exists updated_at timestamptz not null default now();

do $$ begin
  alter table public.questions add constraint questions_difficulty_check check (difficulty in ('easy', 'medium', 'hard'));
exception when duplicate_object then null;
end $$;
do $$ begin
  alter table public.questions add constraint questions_status_check check (status in ('published', 'draft', 'hidden'));
exception when duplicate_object then null;
end $$;

update public.questions q set category_id = c.id
from public.categories c where c.name = q.category and q.category_id is null;

create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null,
  label text not null,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

insert into public.app_settings(key,value,label) values
  ('reward_icons', '10'::jsonb, 'Icon nhận từ quảng cáo'),
  ('unlock_cost', '20'::jsonb, 'Icon cần để mở câu hỏi'),
  ('free_question_limit', '10'::jsonb, 'Số câu hỏi miễn phí')
on conflict (key) do nothing;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = '' as $$
  select exists(select 1 from public.profiles where id = (select auth.uid()) and role = 'admin' and not is_banned)
$$;

create or replace function public.sync_question_category()
returns trigger language plpgsql set search_path = '' as $$
begin
  if new.category_id is not null then
    select name into new.category from public.categories where id = new.category_id;
  end if;
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists sync_question_category_trigger on public.questions;
create trigger sync_question_category_trigger before insert or update on public.questions
for each row execute function public.sync_question_category();

create or replace function public.sync_category_name()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  update public.questions set category = new.name where category_id = new.id;
  update public.categories set updated_at = now() where id = new.id and updated_at = old.updated_at;
  return new;
end $$;

drop trigger if exists sync_category_name_trigger on public.categories;
create trigger sync_category_name_trigger after update of name on public.categories
for each row execute function public.sync_category_name();

alter table public.categories enable row level security;
alter table public.app_settings enable row level security;

drop policy if exists "User reads own profile" on public.profiles;
drop policy if exists "Authenticated users read questions" on public.questions;
drop policy if exists "User reads own progress" on public.user_progress;
drop policy if exists "User reads own unlocks" on public.user_unlocks;

create policy "Users read own profile and admins read all" on public.profiles
for select to authenticated using ((select auth.uid()) = id or public.is_admin());

create policy "Users read published questions and admins read all" on public.questions
for select to authenticated using (status = 'published' or public.is_admin());
create policy "Admins insert questions" on public.questions
for insert to authenticated with check (public.is_admin());
create policy "Admins update questions" on public.questions
for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "Admins delete questions" on public.questions
for delete to authenticated using (public.is_admin());

create policy "Authenticated users read categories" on public.categories
for select to authenticated using (true);
create policy "Admins insert categories" on public.categories
for insert to authenticated with check (public.is_admin());
create policy "Admins update categories" on public.categories
for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "Admins delete unused categories" on public.categories
for delete to authenticated using (public.is_admin());

create policy "Users read own progress and admins read all" on public.user_progress
for select to authenticated using ((select auth.uid()) = user_id or public.is_admin());
create policy "Users read own unlocks and admins read all" on public.user_unlocks
for select to authenticated using ((select auth.uid()) = user_id or public.is_admin());

create policy "Authenticated users read settings" on public.app_settings
for select to authenticated using (true);
create policy "Admins update settings" on public.app_settings
for update to authenticated using (public.is_admin()) with check (public.is_admin());

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.profiles (id, display_name, role)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', new.raw_user_meta_data ->> 'full_name', 'Người chơi'), 'user');
  return new;
end;
$$;

create or replace function public.claim_reward()
returns integer language plpgsql security definer set search_path = '' as $$
declare new_balance integer; reward_amount integer;
begin
  if (select auth.uid()) is null then raise exception 'Authentication required'; end if;
  if exists(select 1 from public.profiles where id=(select auth.uid()) and is_banned) then raise exception 'Account is locked'; end if;
  select coalesce((value #>> '{}')::integer, 10) into reward_amount from public.app_settings where key='reward_icons';
  update public.profiles set icon_balance = icon_balance + coalesce(reward_amount,10)
  where id = (select auth.uid()) returning icon_balance into new_balance;
  if new_balance is null then raise exception 'Profile not found'; end if;
  return new_balance;
end;
$$;

create or replace function public.unlock_question(target_question_id bigint)
returns integer language plpgsql security definer set search_path = '' as $$
declare current_balance integer; question_order integer; unlock_price integer; free_limit integer;
begin
  if (select auth.uid()) is null then raise exception 'Authentication required'; end if;
  if exists(select 1 from public.profiles where id=(select auth.uid()) and is_banned) then raise exception 'Account is locked'; end if;
  select sort_order into question_order from public.questions where id=target_question_id and status='published';
  if question_order is null then raise exception 'Question not found'; end if;
  select coalesce((value #>> '{}')::integer,20) into unlock_price from public.app_settings where key='unlock_cost';
  select coalesce((value #>> '{}')::integer,10) into free_limit from public.app_settings where key='free_question_limit';
  select icon_balance into current_balance from public.profiles where id=(select auth.uid()) for update;
  if question_order <= coalesce(free_limit,10) then return current_balance; end if;
  if exists(select 1 from public.user_unlocks where user_id=(select auth.uid()) and question_id=target_question_id) then return current_balance; end if;
  if current_balance < coalesce(unlock_price,20) then raise exception 'Not enough icons'; end if;
  insert into public.user_unlocks(user_id,question_id) values((select auth.uid()),target_question_id);
  update public.profiles set icon_balance=icon_balance-coalesce(unlock_price,20)
  where id=(select auth.uid()) returning icon_balance into current_balance;
  return current_balance;
end;
$$;

create or replace function public.submit_answer(target_question_id bigint, chosen_answer integer)
returns boolean language plpgsql security definer set search_path = '' as $$
declare answer_index integer; answer_is_correct boolean; question_order integer; free_limit integer;
begin
  if (select auth.uid()) is null then raise exception 'Authentication required'; end if;
  if exists(select 1 from public.profiles where id=(select auth.uid()) and is_banned) then raise exception 'Account is locked'; end if;
  if chosen_answer < 0 or chosen_answer > 3 then raise exception 'Invalid answer'; end if;
  select correct_answer,sort_order into answer_index,question_order from public.questions where id=target_question_id and status='published';
  if answer_index is null then raise exception 'Question not found'; end if;
  select coalesce((value #>> '{}')::integer,10) into free_limit from public.app_settings where key='free_question_limit';
  if question_order > coalesce(free_limit,10) and not exists(select 1 from public.user_unlocks where user_id=(select auth.uid()) and question_id=target_question_id) then raise exception 'Question is locked'; end if;
  answer_is_correct := chosen_answer=answer_index;
  insert into public.user_progress(user_id,question_id,selected_answer,is_correct,completed_at)
  values((select auth.uid()),target_question_id,chosen_answer,answer_is_correct,now())
  on conflict(user_id,question_id) do update set selected_answer=excluded.selected_answer,is_correct=excluded.is_correct,completed_at=excluded.completed_at;
  return answer_is_correct;
end;
$$;

create or replace function public.admin_dashboard()
returns jsonb language sql stable security definer set search_path = '' as $$
  select case when public.is_admin() then jsonb_build_object(
    'users',(select count(*) from auth.users where deleted_at is null),
    'questions',(select count(*) from public.questions),
    'categories',(select count(*) from public.categories),
    'published',(select count(*) from public.questions where status='published'),
    'inactive_questions',(select count(*) from public.questions where status<>'published'),
    'answers',(select count(*) from public.user_progress)
  ) else (select null::jsonb) end
$$;

create or replace function public.admin_list_users()
returns table(id uuid,email text,display_name text,role text,icon_balance integer,is_banned boolean,created_at timestamptz,completed_count bigint)
language plpgsql stable security definer set search_path = '' as $$
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  return query select u.id,u.email::text,p.display_name,p.role,p.icon_balance,p.is_banned,p.created_at,
    (select count(*) from public.user_progress up where up.user_id=u.id)
  from auth.users u join public.profiles p on p.id=u.id where u.deleted_at is null order by p.created_at desc;
end $$;

create or replace function public.admin_set_user_icons(target_user_id uuid,new_balance integer)
returns void language plpgsql security definer set search_path = '' as $$
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  if new_balance < 0 then raise exception 'Invalid balance'; end if;
  update public.profiles set icon_balance=new_balance where id=target_user_id;
end $$;

create or replace function public.admin_set_user_banned(target_user_id uuid,banned boolean)
returns void language plpgsql security definer set search_path = '' as $$
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  if target_user_id=(select auth.uid()) then raise exception 'Cannot lock your own account'; end if;
  update public.profiles set is_banned=banned where id=target_user_id;
  update auth.users set banned_until=case when banned then now()+interval '100 years' else null end,updated_at=now() where id=target_user_id;
end $$;

revoke all on public.categories,public.app_settings from anon,authenticated;
grant select on public.categories,public.app_settings to authenticated;
grant insert,update,delete on public.categories to authenticated;
grant update on public.app_settings to authenticated;
grant usage,select on sequence public.categories_id_seq to authenticated;
grant insert,update,delete on public.questions to authenticated;

revoke execute on function public.is_admin() from public,anon;
revoke execute on function public.admin_dashboard() from public,anon;
revoke execute on function public.admin_list_users() from public,anon;
revoke execute on function public.admin_set_user_icons(uuid,integer) from public,anon;
revoke execute on function public.admin_set_user_banned(uuid,boolean) from public,anon;
grant execute on function public.is_admin(),public.admin_dashboard(),public.admin_list_users(),public.admin_set_user_icons(uuid,integer),public.admin_set_user_banned(uuid,boolean) to authenticated;

-- Bao dam hai tai khoan test hien co dung email/role ma khong tao moi hay doi id.
update auth.users set email='nguyenvank18a2@gmail.com',raw_app_meta_data=coalesce(raw_app_meta_data,'{}'::jsonb)||'{"role":"admin"}'::jsonb,updated_at=now()
where id='10000000-0000-4000-8000-000000000001'::uuid;
update auth.identities set identity_data=jsonb_set(identity_data,'{email}','"nguyenvank18a2@gmail.com"'::jsonb),updated_at=now()
where user_id='10000000-0000-4000-8000-000000000001'::uuid and provider='email';
update public.profiles set role='admin' where id='10000000-0000-4000-8000-000000000001'::uuid;

update auth.users set email='user@quiz.local',raw_app_meta_data=coalesce(raw_app_meta_data,'{}'::jsonb)||'{"role":"user"}'::jsonb,updated_at=now()
where id='10000000-0000-4000-8000-000000000002'::uuid;
update auth.identities set identity_data=jsonb_set(identity_data,'{email}','"user@quiz.local"'::jsonb),updated_at=now()
where user_id='10000000-0000-4000-8000-000000000002'::uuid and provider='email';
update public.profiles set role='user' where id='10000000-0000-4000-8000-000000000002'::uuid;

-- Hardening sau khi chay Supabase Advisors.
revoke execute on function public.sync_category_name() from public, anon, authenticated;
revoke execute on function public.sync_question_category() from public, anon, authenticated;
revoke execute on function public.rls_auto_enable() from public, anon, authenticated;

create index if not exists questions_category_id_idx on public.questions(category_id);
create index if not exists app_settings_updated_by_idx on public.app_settings(updated_by);
create index if not exists user_progress_question_id_idx on public.user_progress(question_id);
create index if not exists user_unlocks_question_id_idx on public.user_unlocks(question_id);
