-- Chạy toàn bộ file này một lần trong Supabase SQL Editor.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Người chơi',
  icon_balance integer not null default 0 check (icon_balance >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  question text not null,
  choices jsonb not null check (jsonb_array_length(choices) = 4),
  correct_answer integer not null check (correct_answer between 0 and 3),
  explanation text not null,
  category text not null,
  sort_order integer not null unique check (sort_order > 0),
  created_at timestamptz not null default now()
);

create table if not exists public.user_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete cascade,
  selected_answer integer not null check (selected_answer between 0 and 3),
  is_correct boolean not null,
  completed_at timestamptz not null default now(),
  primary key (user_id, question_id)
);

create table if not exists public.user_unlocks (
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete cascade,
  unlocked_at timestamptz not null default now(),
  primary key (user_id, question_id)
);

create index if not exists user_progress_user_id_idx on public.user_progress(user_id);
create index if not exists user_unlocks_user_id_idx on public.user_unlocks(user_id);

alter table public.profiles enable row level security;
alter table public.questions enable row level security;
alter table public.user_progress enable row level security;
alter table public.user_unlocks enable row level security;

revoke all on table public.profiles, public.questions, public.user_progress, public.user_unlocks from anon, authenticated;
grant select on public.profiles, public.questions, public.user_progress, public.user_unlocks to authenticated;

create policy "User reads own profile" on public.profiles for select to authenticated using ((select auth.uid()) = id);
create policy "Authenticated users read questions" on public.questions for select to authenticated using (true);
create policy "User reads own progress" on public.user_progress for select to authenticated using ((select auth.uid()) = user_id);
create policy "User reads own unlocks" on public.user_unlocks for select to authenticated using ((select auth.uid()) = user_id);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', new.raw_user_meta_data ->> 'full_name', 'Người chơi'));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

-- DEV / MVP rewarded-ad simulator: mỗi lần gọi sẽ cộng 10 icon.
create or replace function public.claim_reward()
returns integer language plpgsql security definer set search_path = '' as $$
declare new_balance integer;
begin
  if (select auth.uid()) is null then raise exception 'Authentication required'; end if;
  update public.profiles set icon_balance = icon_balance + 10 where id = (select auth.uid()) returning icon_balance into new_balance;
  if new_balance is null then raise exception 'Profile not found'; end if;
  return new_balance;
end;
$$;

create or replace function public.unlock_question(target_question_id bigint)
returns integer language plpgsql security definer set search_path = '' as $$
declare current_balance integer; question_order integer;
begin
  if (select auth.uid()) is null then raise exception 'Authentication required'; end if;
  select sort_order into question_order from public.questions where id = target_question_id;
  if question_order is null then raise exception 'Question not found'; end if;
  select icon_balance into current_balance from public.profiles where id = (select auth.uid()) for update;
  if question_order <= 10 then return current_balance; end if;
  if exists (select 1 from public.user_unlocks where user_id = (select auth.uid()) and question_id = target_question_id) then return current_balance; end if;
  if current_balance < 20 then raise exception 'Not enough icons'; end if;
  insert into public.user_unlocks(user_id, question_id) values ((select auth.uid()), target_question_id);
  update public.profiles set icon_balance = icon_balance - 20 where id = (select auth.uid()) returning icon_balance into current_balance;
  return current_balance;
end;
$$;

create or replace function public.submit_answer(target_question_id bigint, chosen_answer integer)
returns boolean language plpgsql security definer set search_path = '' as $$
declare answer_index integer; answer_is_correct boolean; question_order integer;
begin
  if (select auth.uid()) is null then raise exception 'Authentication required'; end if;
  if chosen_answer < 0 or chosen_answer > 3 then raise exception 'Invalid answer'; end if;
  select correct_answer, sort_order into answer_index, question_order from public.questions where id = target_question_id;
  if answer_index is null then raise exception 'Question not found'; end if;
  if question_order > 10 and not exists (select 1 from public.user_unlocks where user_id = (select auth.uid()) and question_id = target_question_id) then raise exception 'Question is locked'; end if;
  answer_is_correct := chosen_answer = answer_index;
  insert into public.user_progress(user_id, question_id, selected_answer, is_correct, completed_at)
  values ((select auth.uid()), target_question_id, chosen_answer, answer_is_correct, now())
  on conflict (user_id, question_id) do update set selected_answer=excluded.selected_answer, is_correct=excluded.is_correct, completed_at=excluded.completed_at;
  return answer_is_correct;
end;
$$;

revoke execute on function public.handle_new_user() from public, anon, authenticated;
revoke execute on function public.claim_reward() from public, anon;
revoke execute on function public.unlock_question(bigint) from public, anon;
revoke execute on function public.submit_answer(bigint, integer) from public, anon;
grant execute on function public.claim_reward() to authenticated;
grant execute on function public.unlock_question(bigint) to authenticated;
grant execute on function public.submit_answer(bigint, integer) to authenticated;

insert into public.questions (question, choices, correct_answer, explanation, category, sort_order) values
('Chiến dịch Điện Biên Phủ kết thúc vào năm nào?', '["1952","1953","1954","1955"]', 2, 'Chiến dịch Điện Biên Phủ kết thúc thắng lợi ngày 7 tháng 5 năm 1954.', 'Lịch sử', 1),
('Đỉnh núi cao nhất Việt Nam là gì?', '["Fansipan","Ngọc Linh","Bạch Mã","Langbiang"]', 0, 'Fansipan cao 3.143 mét và được gọi là nóc nhà Đông Dương.', 'Địa lý', 2),
('Nguyên tố hóa học nào có ký hiệu O?', '["Vàng","Oxy","Sắt","Bạc"]', 1, 'O là ký hiệu hóa học của nguyên tố oxy.', 'Khoa học', 3),
('Thủ đô của Việt Nam là gì?', '["Thành phố Hồ Chí Minh","Đà Nẵng","Hà Nội","Huế"]', 2, 'Hà Nội là thủ đô của nước Cộng hòa xã hội chủ nghĩa Việt Nam.', 'Địa lý', 4),
('Loài vật nào được gọi là chúa sơn lâm?', '["Voi","Hổ","Gấu","Báo"]', 1, 'Hổ thường được gọi là chúa sơn lâm trong văn hóa dân gian.', 'Thế giới', 5),
('Một tuần có bao nhiêu ngày?', '["5","6","7","8"]', 2, 'Một tuần có 7 ngày, từ thứ Hai đến Chủ nhật.', 'Đời sống', 6),
('Hành tinh nào gần Mặt Trời nhất?', '["Sao Kim","Trái Đất","Sao Hỏa","Sao Thủy"]', 3, 'Sao Thủy là hành tinh nằm gần Mặt Trời nhất.', 'Khoa học', 7),
('Tác giả truyện Dế Mèn phiêu lưu ký là ai?', '["Tô Hoài","Nam Cao","Ngô Tất Tố","Xuân Diệu"]', 0, 'Nhà văn Tô Hoài là tác giả của Dế Mèn phiêu lưu ký.', 'Văn học', 8),
('Màu nào được tạo ra khi trộn xanh dương và vàng?', '["Tím","Cam","Xanh lá","Đỏ"]', 2, 'Theo cách pha màu cơ bản, xanh dương kết hợp với vàng tạo thành xanh lá.', 'Nghệ thuật', 9),
('Nước đóng băng ở bao nhiêu độ C?', '["0°C","10°C","50°C","100°C"]', 0, 'Ở áp suất khí quyển tiêu chuẩn, nước đóng băng tại 0°C.', 'Khoa học', 10),
('Nhạc cụ nào thường có 88 phím?', '["Đàn guitar","Đàn piano","Đàn tranh","Sáo"]', 1, 'Một cây đàn piano tiêu chuẩn hiện đại thường có 88 phím.', 'Âm nhạc', 11),
('Quốc kỳ Việt Nam có ngôi sao màu gì?', '["Trắng","Xanh","Vàng","Đen"]', 2, 'Quốc kỳ Việt Nam có nền đỏ và một ngôi sao vàng năm cánh.', 'Đời sống', 12),
('Con vật nào là động vật có vú sống dưới biển?', '["Cá mập","Cá heo","Cá ngừ","Bạch tuộc"]', 1, 'Cá heo thở bằng phổi và nuôi con bằng sữa nên là động vật có vú.', 'Thế giới', 13),
('Số nào là số nguyên tố?', '["9","15","17","21"]', 2, '17 chỉ chia hết cho 1 và chính nó nên là số nguyên tố.', 'Toán học', 14),
('Châu lục lớn nhất thế giới là châu nào?', '["Châu Âu","Châu Phi","Châu Á","Châu Mỹ"]', 2, 'Châu Á là châu lục lớn nhất cả về diện tích và dân số.', 'Địa lý', 15)
on conflict (sort_order) do update set question=excluded.question, choices=excluded.choices, correct_answer=excluded.correct_answer, explanation=excluded.explanation, category=excluded.category;
