"use client";
import { ArrowLeft,CheckCircle2,ChevronRight,CircleDollarSign,FileText,LockKeyhole,LogOut,ShieldCheck,UserRound } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect,useMemo,useState } from "react";
import { useAuth } from "@/components/auth-provider";
import { LoadingScreen } from "@/components/loading-screen";
import { createClient } from "@/lib/supabase/client";
import type { Profile } from "@/lib/types";

export function AccountScreen(){const{user}=useAuth();const router=useRouter();const supabase=useMemo(()=>createClient(),[]);const[profile,setProfile]=useState<Profile|null>(null);const[completed,setCompleted]=useState(0);const[unlocked,setUnlocked]=useState(0);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 useEffect(()=>{async function load(){if(!supabase||!user)return;const[{data:p,error:pe},{count:c},{count:u}]=await Promise.all([supabase.from("profiles").select("*").eq("id",user.id).single(),supabase.from("user_progress").select("*",{count:"exact",head:true}).eq("user_id",user.id),supabase.from("user_unlocks").select("*",{count:"exact",head:true}).eq("user_id",user.id)]);if(pe)setError("Không thể tải thông tin tài khoản.");else{setProfile(p);setCompleted(c??0);setUnlocked(u??0)}setLoading(false)}load()},[supabase,user]);
 async function logout(){if(!supabase)return;await supabase.auth.signOut();router.replace("/login")}
 if(loading)return <LoadingScreen text="Đang tải tài khoản..."/>;return <main className="min-h-screen"><header className="bg-[#f0f3ff]"><div className="content-width relative flex h-14 items-center justify-center"><Link href="/" aria-label="Quay lại" className="absolute left-0 p-2 text-[var(--primary)]"><ArrowLeft/></Link><h1 className="font-bold text-[var(--primary)]">Tài khoản</h1></div></header><div className="content-width py-6 text-center"><div className="mx-auto flex size-20 items-center justify-center rounded-full border-4 border-[#dfe6ff] bg-[var(--primary)] text-white"><UserRound size={44}/></div><h2 className="mt-3 text-2xl font-bold">{profile?.display_name||"Người chơi"}</h2><p className="mt-1 text-sm text-[var(--muted)]">{user?.email}</p>{error&&<p className="mt-4 text-red-700">{error}</p>}<div className="mt-8 grid grid-cols-3 gap-3"><Stat icon={<CircleDollarSign fill="#ffd229" color="#fff"/>} value={profile?.icon_balance??0} label="Số icon hiện có" color="#4b4cdf"/><Stat icon={<CheckCircle2 fill="#07998f" color="#fff"/>} value={completed} label="Câu đố hoàn thành" color="#047d77"/><Stat icon={<LockKeyhole fill="#6869ee" color="#fff"/>} value={unlocked} label="Câu đố mở khóa" color="#6967ed"/></div><div className="mt-7 overflow-hidden rounded-xl border border-[var(--border)] bg-white text-left"><MenuRow icon={<FileText/>} label="Điều khoản sử dụng"/><MenuRow icon={<ShieldCheck/>} label="Chính sách bảo mật"/></div><button type="button" onClick={logout} className="mt-8 flex min-h-12 w-full items-center justify-center gap-2 rounded-full bg-[#cc1717] font-bold text-white shadow-[0_4px_0_#9c1010]"><LogOut size={19}/>Đăng xuất</button></div></main>}
function Stat({icon,value,label,color}:{icon:React.ReactNode;value:number;label:string;color:string}){return <div className="rounded-xl border border-[#ced4e7] bg-[#eaf0ff] px-2 py-3"><div className="mx-auto flex size-9 items-center justify-center">{icon}</div><p className="mt-2 text-xl font-bold" style={{color}}>{value}</p><p className="mt-1 text-[11px] font-medium leading-4">{label}</p></div>}
function MenuRow({icon,label}:{icon:React.ReactNode;label:string}){return <button type="button" className="flex min-h-14 w-full items-center gap-3 border-b border-[var(--border)] px-4 font-semibold last:border-b-0"><span aria-hidden="true">{icon}</span><span className="flex-1">{label}</span><ChevronRight size={18}/></button>}
