"use client";
import { ArrowLeft,CheckCircle2,XCircle } from "lucide-react";
import Link from "next/link";
import { useParams,useRouter } from "next/navigation";
import { useEffect,useMemo,useState } from "react";
import { CoinBadge } from "@/components/coin-badge";
import { LoadingScreen } from "@/components/loading-screen";
import { useAuth } from "@/components/auth-provider";
import { createClient } from "@/lib/supabase/client";
import type { Question } from "@/lib/types";

export function QuizScreen(){const params=useParams<{id:string}>();const router=useRouter();const{user}=useAuth();const supabase=useMemo(()=>createClient(),[]);const[question,setQuestion]=useState<Question|null>(null);const[balance,setBalance]=useState(0);const[total,setTotal]=useState(1);const[freeLimit,setFreeLimit]=useState(10);const[selected,setSelected]=useState<number|null>(null);const[checked,setChecked]=useState(false);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 useEffect(()=>{async function load(){if(!supabase||!user)return;const id=Number(params.id);const[{data:q,error:qe},{data:p},{data:u},{count},{data:s}]=await Promise.all([supabase.from("questions").select("*").eq("id",id).single(),supabase.from("profiles").select("icon_balance").eq("id",user.id).single(),supabase.from("user_unlocks").select("question_id").eq("user_id",user.id).eq("question_id",id).maybeSingle(),supabase.from("questions").select("*",{count:"exact",head:true}),supabase.from("app_settings").select("value").eq("key","free_question_limit").maybeSingle()]);if(qe){setError("Không tìm thấy câu hỏi này.");setLoading(false);return}const limit=Number(s?.value??10);if(q.sort_order>limit&&!u){router.replace("/");return}setQuestion(q as Question);setBalance(p?.icon_balance??0);setTotal(count??1);setFreeLimit(limit);setLoading(false)}load()},[params.id,router,supabase,user]);
 async function checkAnswer(){if(selected===null||!question||!supabase||!user)return;const{error:saveError}=await supabase.rpc("submit_answer",{target_question_id:question.id,chosen_answer:selected});if(saveError){setError("Không thể lưu kết quả. Vui lòng thử lại.");return}setChecked(true)}
 async function nextQuestion(){if(!question||!supabase)return;const{data:next}=await supabase.from("questions").select("id,sort_order").gt("sort_order",question.sort_order).order("sort_order").limit(1).maybeSingle();if(!next){router.push("/");return}if(next.sort_order>freeLimit){const{data:unlock}=await supabase.from("user_unlocks").select("question_id").eq("question_id",next.id).maybeSingle();if(!unlock){router.push("/");return}}router.push(`/quiz/${next.id}`)}
 if(loading)return <LoadingScreen text="Đang tải câu hỏi..."/>;if(!question)return <main className="content-width py-20 text-center"><p>{error}</p><Link href="/" className="mt-4 inline-block text-[var(--primary)] underline">Về trang chủ</Link></main>;
 const correct=selected===question.correct_answer;return <main className="content-width py-5 sm:py-8"><header className="flex items-center justify-between"><Link href="/" aria-label="Quay lại" className="rounded-full p-2"><ArrowLeft/></Link><CoinBadge balance={balance}/></header><div className="mt-5 flex items-center justify-between text-sm"><span>Câu hỏi {question.sort_order}/{total}</span><span className="text-[var(--primary)]">{question.category}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#dce5fb]"><div className="h-full rounded-full bg-gradient-to-r from-[#4f4ee0] to-[#0c8d8a]" style={{width:`${Math.min(100,(question.sort_order/total)*100)}%`}}/></div>
 <section className="card-shadow mt-6 rounded-xl border-2 border-[#5b5bf0] bg-white px-4 py-6 sm:px-6"><h1 className="text-center text-[22px] font-bold sm:text-2xl">{question.question}</h1><div className="mt-7 space-y-3">{question.choices.map((choice,index)=>{const chosen=selected===index;const isRight=index===question.correct_answer;let style=chosen?"border-[var(--primary)] bg-[#eef0ff]":"border-[#d0d2e1] bg-white";if(checked&&isRight)style="border-[#18a959] bg-green-50";else if(checked&&chosen&&!isRight)style="border-red-500 bg-red-50";return <button key={choice} type="button" disabled={checked} onClick={()=>setSelected(index)} className={`flex min-h-[52px] w-full items-center gap-3 rounded-lg border-2 px-3 text-left font-semibold ${style}`}><span className="flex size-7 shrink-0 items-center justify-center rounded-full bg-[#eef2fa] text-sm text-[#3561a4]">{String.fromCharCode(65+index)}</span>{choice}</button>})}</div>
 {checked&&<div className={`mt-6 rounded-xl p-4 ${correct?"bg-green-50 text-green-800":"bg-red-50 text-red-800"}`} role="status"><p className="flex items-center gap-2 text-lg font-bold">{correct?<CheckCircle2/>:<XCircle/>}{correct?"Chính xác!":"Chưa chính xác"}</p><h2 className="mt-3 font-bold">Giải thích</h2><p className="mt-1 leading-6">{question.explanation}</p></div>}</section>{error&&<p className="mt-4 text-center text-sm text-red-700" role="alert">{error}</p>}<button type="button" disabled={selected===null} onClick={checked?nextQuestion:checkAnswer} className="primary-button mt-7 w-full">{checked?(question.sort_order>=total?"Về danh sách":"Câu tiếp theo"):"Kiểm tra đáp án"}</button></main>}
