"use client";
import {Activity,FileQuestion,FolderTree,Send,Users} from "lucide-react";
import {useEffect,useMemo,useState} from "react";
import {AdminShell,EmptyState} from "@/components/admin/admin-shell";
import {LoadingScreen} from "@/components/loading-screen";
import {createClient} from "@/lib/supabase/client";

type Stats={users:number;questions:number;categories:number;published:number;inactive_questions:number;answers:number};
type Recent={completed_at:string;is_correct:boolean;question_id:number;user_id:string};
export function AdminDashboard(){const supabase=useMemo(()=>createClient(),[]);const[stats,setStats]=useState<Stats|null>(null);const[recent,setRecent]=useState<Recent[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");useEffect(()=>{async function load(){if(!supabase)return;const[{data,error:e},{data:r}]=await Promise.all([supabase.rpc("admin_dashboard"),supabase.from("user_progress").select("user_id,question_id,is_correct,completed_at").order("completed_at",{ascending:false}).limit(6)]);if(e)setError("Không thể tải thống kê quản trị.");else setStats(data as unknown as Stats);setRecent((r??[]) as Recent[]);setLoading(false)}load()},[supabase]);if(loading)return <LoadingScreen text="Đang tải dashboard..."/>;const cards=[{label:"Tổng user",value:stats?.users??0,icon:Users},{label:"Tổng câu hỏi",value:stats?.questions??0,icon:FileQuestion},{label:"Categories",value:stats?.categories??0,icon:FolderTree},{label:"Đã published",value:stats?.published??0,icon:Send},{label:"Draft / hidden",value:stats?.inactive_questions??0,icon:FileQuestion},{label:"Lượt trả lời",value:stats?.answers??0,icon:Activity}];return <AdminShell title="Dashboard" description="Tổng quan hoạt động hệ thống">{error&&<p className="mb-4 rounded-lg bg-red-50 p-3 text-red-700">{error}</p>}<section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(({label,value,icon:Icon})=><article key={label} className="rounded-xl border border-[#e1e3ee] bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><p className="text-sm font-semibold text-[var(--muted)]">{label}</p><span className="rounded-lg bg-[#eef0ff] p-2 text-[var(--primary)]"><Icon size={20}/></span></div><p className="mt-3 text-3xl font-bold">{value}</p></article>)}</section><section className="mt-7"><h2 className="mb-3 text-lg font-bold">Hoạt động gần đây</h2>{recent.length===0?<EmptyState text="Chưa có lượt trả lời nào."/>:<div className="overflow-hidden rounded-xl border border-[#e1e3ee] bg-white">{recent.map((item,index)=><div key={`${item.user_id}-${item.question_id}-${index}`} className="flex items-center justify-between border-b border-[#eceef5] px-4 py-3 last:border-0"><div><p className="font-semibold">Câu hỏi #{item.question_id}</p><p className="text-xs text-[var(--muted)]">User {item.user_id.slice(0,8)}… · {new Date(item.completed_at).toLocaleString("vi-VN")}</p></div><span className={`rounded-full px-2 py-1 text-xs font-bold ${item.is_correct?"bg-green-50 text-green-700":"bg-red-50 text-red-700"}`}>{item.is_correct?"Đúng":"Sai"}</span></div>)}</div>}</section></AdminShell>}
