"use client";
import {Save} from "lucide-react";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {AdminNotice,AdminShell} from "@/components/admin/admin-shell";
import {LoadingScreen} from "@/components/loading-screen";
import {useAuth} from "@/components/auth-provider";
import {createClient} from "@/lib/supabase/client";

type Setting={key:string;value:number;label:string;updated_at:string};
export function SettingsManager(){const{user}=useAuth();const supabase=useMemo(()=>createClient(),[]);const[items,setItems]=useState<Setting[]>([]);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[notice,setNotice]=useState("");const[error,setError]=useState("");useEffect(()=>{async function load(){if(!supabase)return;const{data,error:e}=await supabase.from("app_settings").select("key,value,label,updated_at").order("key");if(e)setError("Không thể tải settings.");else setItems((data??[]).map(x=>({...x,value:Number(x.value)})) as Setting[]);setLoading(false)}load()},[supabase]);async function save(e:FormEvent){e.preventDefault();if(!supabase||items.some(x=>!Number.isInteger(x.value)||x.value<0)){setError("Các giá trị phải là số nguyên không âm.");return}setSaving(true);setError("");const results=await Promise.all(items.map(item=>supabase.from("app_settings").update({value:item.value,updated_at:new Date().toISOString(),updated_by:user?.id}).eq("key",item.key)));setSaving(false);if(results.some(x=>x.error))setError("Không thể lưu toàn bộ settings.");else setNotice("Đã lưu settings.")}if(loading)return <LoadingScreen text="Đang tải settings..."/>;return <AdminShell title="Settings" description="Cấu hình phần thưởng và quiz"><AdminNotice message={notice}/><AdminNotice message={error} type="error"/><form onSubmit={save} className="max-w-2xl rounded-xl border border-[#e1e3ee] bg-white p-5"><div className="space-y-4">{items.map((item,index)=><label key={item.key} className="block"><span className="font-bold">{item.label}</span><span className="ml-2 text-xs text-[var(--muted)]">({item.key})</span><input type="number" min={0} step={1} value={item.value} onChange={e=>setItems(current=>current.map((x,i)=>i===index?{...x,value:Number(e.target.value)}:x))} className="mt-2 min-h-11 w-full rounded-lg border border-[#d5d8e6] px-3"/></label>)}</div><button disabled={saving} className="primary-button mt-6 px-6"><Save size={18}/>{saving?"Đang lưu...":"Lưu thay đổi"}</button></form></AdminShell>}
